#!/usr/bin/env python3
#
# Copyright (c) 2026 by Clemens Rabe <clemens.rabe@clemensrabe.de>
# All rights reserved.
# This file is part of stl2scad (https://github.com/seeraven/stl2scad)
# and is released under the "BSD 3-Clause License". Please see the LICENSE file
# that is included as part of this package.
#
"""Tool for using STL files with OpenSCAD."""

# -----------------------------------------------------------------------------
# Module Import
# -----------------------------------------------------------------------------
import sys

from stl_2_scad.cli import main_cli

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    sys.exit(main_cli())
